"""empty message

Revision ID: 87128d0d47c3
Revises: 
Create Date: 2020-07-05 23:09:48.775716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87128d0d47c3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contenttype",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "lessontype",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "materialtype",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "quiztype",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calendar_url", sa.String(), nullable=True),
        sa.Column("calendar_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "section",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["topic.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedule.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "lesson",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("story", sa.String(), nullable=True),
        sa.Column("motivation", sa.String(), nullable=True),
        sa.Column("lesson_type_id", sa.Integer(), nullable=True),
        sa.Column("parent_lesson_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lesson_type_id"], ["lessontype.id"],),
        sa.ForeignKeyConstraint(["parent_lesson_id"], ["lesson.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "resource",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("content_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["content_type_id"], ["contenttype.id"],),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "slot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedule.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "material",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("brief", sa.Text(), nullable=True),
        sa.Column("minute_estimate", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("material_type_id", sa.Integer(), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["material_type_id"], ["materialtype.id"],),
        sa.ForeignKeyConstraint(["parent_id"], ["material.id"],),
        sa.ForeignKeyConstraint(["resource_id"], ["resource.id"],),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "sequence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"],),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "timer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("finish", sa.DateTime(), nullable=True),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "lessonmaterialm2m",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"],),
        sa.ForeignKeyConstraint(["material_id"], ["material.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "quiz",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("quiz_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["material_id"], ["material.id"],),
        sa.ForeignKeyConstraint(["quiz_type_id"], ["quiztype.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "quizlog",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("finish", sa.DateTime(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("quiz_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quizlog")
    op.drop_table("quiz")
    op.drop_table("lessonmaterialm2m")
    op.drop_table("timer")
    op.drop_table("sequence")
    op.drop_table("note")
    op.drop_table("material")
    op.drop_table("slot")
    op.drop_table("resource")
    op.drop_table("lesson")
    op.drop_table("course")
    op.drop_table("topic")
    op.drop_table("section")
    op.drop_table("schedule")
    op.drop_table("quiztype")
    op.drop_table("materialtype")
    op.drop_table("lessontype")
    op.drop_table("contenttype")
    # ### end Alembic commands ###
